### ISSUE TITLE
Create a Docker image for Suez

### ISSUE THREAD

**Issue by martindsouza** [fuzziebrain/suez#1]

**Comment by martindsouza** [comment]
@fuzziebrain once/if you accept my pull request (#3) you'll need to create the docker hub image and ensure the `README.md` file is correct with the `docker pull` URL

**Comment by fuzziebrain** [comment]
Will track this in #5 . Closing this issue since it's done.

**Comment by fuzziebrain** [comment]
@martindsouza The image has been built on Docker Hub. It has also been setup to build automatically. The image name/reference does not need to be changed in the documentation.
